# Generated by Django 4.2.7 on 2026-03-30 08:15

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LidarDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('point_count', models.BigIntegerField(blank=True, null=True)),
                ('min_height', models.FloatField(blank=True, null=True)),
                ('max_height', models.FloatField(blank=True, null=True)),
                ('avg_point_density', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=150)),
                ('wood_density', models.FloatField(help_text='Wood density in g/cm³', validators=[django.core.validators.MinValueValidator(0)])),
                ('carbon_fraction', models.FloatField(default=0.47, help_text='Carbon fraction of dry biomass (typically 0.47)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Tree species',
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='ForestCompartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_hectares', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('canopy_height_mean', models.FloatField(blank=True, null=True)),
                ('canopy_height_max', models.FloatField(blank=True, null=True)),
                ('canopy_cover_percent', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('height_percentile_95', models.FloatField(blank=True, null=True)),
                ('height_percentile_75', models.FloatField(blank=True, null=True)),
                ('height_percentile_50', models.FloatField(blank=True, null=True)),
                ('crown_volume', models.FloatField(blank=True, null=True)),
                ('foliage_height_diversity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='lidar_app.lidardataset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiomassEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above_ground_biomass', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('below_ground_biomass', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_biomass', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(help_text='Model prediction confidence (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('features_used', models.JSONField()),
                ('estimation_date', models.DateTimeField(auto_now_add=True)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomass_estimates', to='lidar_app.forestcompartment')),
            ],
            options={
                'ordering': ['-estimation_date'],
                'get_latest_by': 'estimation_date',
            },
        ),
    ]
