# Generated by Django 4.2.7 on 2026-03-30 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lidar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above_ground_carbon', models.FloatField(help_text='Above-ground carbon stock in tonnes/ha', validators=[django.core.validators.MinValueValidator(0)])),
                ('below_ground_carbon', models.FloatField(help_text='Below-ground carbon stock in tonnes/ha', validators=[django.core.validators.MinValueValidator(0)])),
                ('soil_organic_carbon', models.FloatField(blank=True, help_text='Soil organic carbon in tonnes/ha', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dead_wood_carbon', models.FloatField(blank=True, help_text='Dead wood carbon in tonnes/ha', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_carbon_stock', models.FloatField(help_text='Total carbon stock in tonnes/ha', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_carbon_tonnes', models.FloatField(help_text='Total carbon in tonnes for the entire compartment', validators=[django.core.validators.MinValueValidator(0)])),
                ('co2_equivalent', models.FloatField(help_text='CO2 equivalent in tonnes (carbon * 3.67)', validators=[django.core.validators.MinValueValidator(0)])),
                ('measurement_date', models.DateField()),
                ('estimation_method', models.CharField(default='LiDAR + ML Model', max_length=100)),
                ('confidence_level', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_stocks', to='lidar_app.forestcompartment')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'get_latest_by': 'measurement_date',
            },
        ),
        migrations.CreateModel(
            name='CarbonCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_standard', models.CharField(choices=[('VCS', 'Verified Carbon Standard'), ('REDD+', 'REDD+'), ('GOLD', 'Gold Standard'), ('CAR', 'Climate Action Reserve'), ('OTHER', 'Other')], max_length=20)),
                ('vintage_year', models.IntegerField(help_text='Year of carbon sequestration')),
                ('verified_carbon_tonnes', models.FloatField(help_text='Verified carbon sequestered in tonnes', validators=[django.core.validators.MinValueValidator(0)])),
                ('co2_equivalent_tonnes', models.FloatField(help_text='CO2 equivalent in tonnes', validators=[django.core.validators.MinValueValidator(0)])),
                ('eligible_credits', models.FloatField(help_text='Number of eligible carbon credits (1 credit = 1 tonne CO2e)', validators=[django.core.validators.MinValueValidator(0)])),
                ('buffer_percentage', models.FloatField(default=20.0, help_text='Buffer reserve percentage (typically 10-20%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('net_credits', models.FloatField(help_text='Net credits after buffer deduction', validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_price_per_credit', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated market price per credit in USD', max_digits=10, null=True)),
                ('potential_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Potential revenue in USD', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PROJECTED', 'Projected'), ('VERIFIED', 'Verified'), ('ISSUED', 'Issued'), ('SOLD', 'Sold'), ('RETIRED', 'Retired')], default='PROJECTED', max_length=20)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('issuance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_credits', to='lidar_app.forestcompartment')),
            ],
            options={
                'ordering': ['-vintage_year'],
            },
        ),
        migrations.CreateModel(
            name='CarbonSequestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_sequestration_rate', models.FloatField(help_text='Annual carbon sequestration rate in tonnes/ha/year', validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_sequestration_total', models.FloatField(help_text='Total annual sequestration in tonnes/year', validators=[django.core.validators.MinValueValidator(0)])),
                ('annual_co2_sequestration', models.FloatField(help_text='Annual CO2 sequestration in tonnes/year', validators=[django.core.validators.MinValueValidator(0)])),
                ('measurement_year', models.IntegerField()),
                ('growth_period_months', models.IntegerField(default=12)),
                ('calculation_method', models.CharField(default='Biomass increment + mortality', max_length=100)),
                ('confidence_level', models.FloatField(default=0.75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequestration_rates', to='lidar_app.forestcompartment')),
            ],
            options={
                'ordering': ['-measurement_year'],
                'unique_together': {('compartment', 'measurement_year')},
            },
        ),
    ]
